import { CSSProperties } from 'react';

const METHOD_COLORS: Record<string, { color: string; bg: string }> = {
  GET:    { color: '#00ff88', bg: 'rgba(0,255,136,0.08)' },
  POST:   { color: '#ff9500', bg: 'rgba(255,149,0,0.08)' },
  PUT:    { color: '#00b4ff', bg: 'rgba(0,180,255,0.08)' },
  PATCH:  { color: '#ff9500', bg: 'rgba(255,149,0,0.08)' },
  DELETE: { color: '#ff006e', bg: 'rgba(255,0,110,0.08)' },
  HEAD:   { color: '#5a8a9a', bg: 'rgba(90,138,154,0.08)' },
};

export const appStyles: Record<string, CSSProperties> = {
  titlebar: {
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
    padding: '0 20px',
    height: '48px',
    flexShrink: 0,
    background: '#060c12',
    borderBottom: '1px solid #0d2d3d',
    position: 'relative',
    overflow: 'hidden',
    zIndex: 10,
  },
  titleLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  titleText: {
    fontFamily: "'Orbitron', monospace",
    fontSize: '16px',
    fontWeight: 900,
    color: '#00f5ff',
    letterSpacing: '4px',
    textShadow: '0 0 20px #00f5ff, 0 0 40px rgba(0,245,255,0.4)',
  },
  titleRight: {
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  titleBtn: {
    background: 'transparent',
    border: '1px solid #00f5ff',
    color: '#00f5ff',
    fontFamily: "'Orbitron', monospace",
    fontSize: '11px',
    fontWeight: 700,
    padding: '8px 16px',
    borderRadius: '2px',
    cursor: 'pointer',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  sidebar: {
    background: '#060c12',
    borderRight: '1px solid #0d2d3d',
    overflowY: 'auto',
    padding: '16px 12px',
  },
  sidebarLabel: {
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '10px',
    fontWeight: 700,
    color: '#2a4a5a',
    letterSpacing: '3px',
    textTransform: 'uppercase',
    padding: '0 8px',
    marginBottom: '8px',
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderRadius: '2px',
    cursor: 'pointer',
    border: '1px solid transparent',
    marginBottom: '2px',
    transition: 'all 0.15s',
  },
  methodBadge: {
    fontSize: '9px',
    fontWeight: 700,
    padding: '2px 5px',
    borderRadius: '2px',
    fontFamily: "'Orbitron', monospace",
    minWidth: '36px',
    textAlign: 'center',
    border: '1px solid',
  },
  sidebarUrl: {
    fontSize: '12px',
    color: '#5a8a9a',
  },
  urlBar: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    padding: '16px 20px',
    background: '#060c12',
    borderBottom: '1px solid #0d2d3d',
  },
  methodSelect: {
    appearance: 'none',
    background: '#0d1e2e',
    fontFamily: "'Orbitron', monospace",
    fontSize: '11px',
    fontWeight: 700,
    padding: '10px 32px 10px 14px',
    borderRadius: '2px',
    cursor: 'pointer',
    letterSpacing: '1px',
    outline: 'none',
    border: '1px solid',
    color: '#00ff88',
    borderColor: 'rgba(0,255,136,0.4)',
  },
  urlInput: {
    flex: 1,
    background: '#0d1e2e',
    border: '1px solid #1a4a5a',
    color: '#00f5ff',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: '13px',
    padding: '10px 14px 10px 36px',
    borderRadius: '2px',
    outline: 'none',
    transition: 'all 0.2s',
  },
  sendBtn: {
    background: 'transparent',
    border: '1px solid #00f5ff',
    color: '#00f5ff',
    fontFamily: "'Orbitron', monospace",
    fontSize: '11px',
    fontWeight: 700,
    padding: '10px 24px',
    borderRadius: '2px',
    cursor: 'pointer',
    letterSpacing: '2px',
    textTransform: 'uppercase',
    transition: 'all 0.2s',
  },
  tabsContainer: {
    display: 'flex',
    borderBottom: '1px solid #0d2d3d',
    background: '#060c12',
    padding: '0 20px',
  },
  tabGroup: {
    display: 'flex',
    gap: '4px',
  },
  tab: {
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '11px',
    fontWeight: 600,
    color: '#2a4a5a',
    letterSpacing: '2px',
    textTransform: 'uppercase',
    padding: '12px 16px',
    cursor: 'pointer',
    borderBottom: '2px solid transparent',
    transition: 'all 0.2s',
    background: 'none',
    border: 'none',
  },
  requestPanel: {
    flex: 1,
    overflow: 'auto',
    background: '#0d1e2e',
    padding: '20px',
  },
  panelContent: {
    padding: '20px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '11px',
    fontWeight: 700,
    color: '#2a4a5a',
    letterSpacing: '3px',
    textTransform: 'uppercase',
    background: '#060c12',
    borderRadius: '2px 2px 0 0',
    borderBottom: '1px solid #0d2d3d',
  },
  addBtn: {
    background: 'transparent',
    border: '1px dashed #1a4a5a',
    color: '#2a4a5a',
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '2px',
    padding: '8px',
    width: '100%',
    cursor: 'pointer',
    borderRadius: '2px',
    textTransform: 'uppercase',
    marginTop: '4px',
    transition: 'all 0.2s',
  },
  kvRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 32px',
    gap: '8px',
    marginBottom: '8px',
    alignItems: 'center',
  },
  kvToggle: {
    width: '32px',
    height: '32px',
    background: 'transparent',
    border: '1px solid #0d2d3d',
    color: '#2a4a5a',
    cursor: 'pointer',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
    transition: 'all 0.2s',
  },
  kvInput: {
    background: '#0d1e2e',
    border: '1px solid #0d2d3d',
    color: '#c8e8f0',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: '12px',
    padding: '8px 12px',
    borderRadius: '2px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  kvDelete: {
    background: 'transparent',
    border: '1px solid #0d2d3d',
    color: '#2a4a5a',
    width: '32px',
    height: '32px',
    borderRadius: '2px',
    cursor: 'pointer',
    fontSize: '16px',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jsonBadge: {
    color: '#ff006e',
    fontSize: '11px',
    fontWeight: 500,
  },
  bodyTextarea: {
    width: '100%',
    minHeight: '200px',
    background: '#0d1e2e',
    border: '1px solid #0d2d3d',
    color: '#00ff88',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: '12px',
    padding: '14px',
    borderRadius: '2px',
    outline: 'none',
    resize: 'vertical',
    lineHeight: 1.6,
  },
  emptyText: {
    padding: '40px',
    textAlign: 'center',
    color: '#2a4a5a',
    fontSize: '11px',
    fontFamily: "'Rajdhani', sans-serif",
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  authItem: {
    padding: '12px 16px',
    borderRadius: '2px',
    color: '#5a8a9a',
    fontSize: '12px',
    fontFamily: "'Rajdhani', sans-serif",
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  authActive: {
    padding: '12px 16px',
    borderRadius: '2px',
    background: 'rgba(0,245,255,0.08)',
    color: '#00f5ff',
    fontSize: '12px',
    fontFamily: "'Rajdhani', sans-serif",
    cursor: 'pointer',
    border: '1px solid rgba(0,245,255,0.3)',
  },
  responseSection: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    background: '#0a1520',
  },
  responseMeta: {
    marginLeft: 'auto',
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
  },
  statusBadge: {
    fontFamily: "'Orbitron', monospace",
    fontSize: '11px',
    fontWeight: 700,
    padding: '3px 10px',
    borderRadius: '2px',
    letterSpacing: '1px',
    border: '1px solid',
  },
  metaText: {
    fontSize: '11px',
    color: '#2a4a5a',
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 500,
    letterSpacing: '1px',
  },
  responseContent: {
    flex: 1,
    padding: '20px',
    overflow: 'auto',
    fontSize: '12px',
    lineHeight: 1.7,
  },
  errorBox: {
    color: '#ff006e',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: '12px',
    padding: '16px',
    border: '1px solid rgba(255,0,110,0.3)',
    borderRadius: '2px',
    background: 'rgba(255,0,110,0.05)',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: '16px',
    opacity: 0.3,
  },
  emptyIcon: {
    width: '48px',
    height: '48px',
    border: '2px solid #00f5ff',
    transform: 'rotate(45deg)',
    position: 'relative',
  },
  emptyMain: {
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '4px',
    textTransform: 'uppercase',
    color: '#5a8a9a',
  },
  loadingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: '20px',
  },
  loadingDots: {
    display: 'flex',
    gap: '8px',
  },
  dotAnim: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    background: '#00f5ff',
  },
  loadingText: {
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '11px',
    fontWeight: 600,
    color: '#00f5ff',
    letterSpacing: '4px',
  },
  jsonPre: {
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-all',
    fontFamily: "'Share Tech Mono', monospace",
    fontSize: '12px',
    lineHeight: 1.7,
    margin: 0,
    padding: '16px',
    background: '#0d1e2e',
    borderRadius: '2px',
  },
  headersList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    background: '#0d2d3d',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  headerRow: {
    display: 'flex',
    padding: '12px 16px',
    background: '#0a1520',
  },
  headerKey: {
    minWidth: '200px',
    fontSize: '12px',
    color: '#c8e8f0',
    fontFamily: "'Share Tech Mono', monospace",
  },
  headerValue: {
    flex: 1,
    fontSize: '12px',
    color: '#00ff88',
    fontFamily: "'Share Tech Mono', monospace",
    wordBreak: 'break-all',
  },
  timeline: {
    padding: '8px 0',
  },
  timelineItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '16px',
  },
  timelineLabel: {
    width: '140px',
    fontSize: '11px',
    color: '#2a4a5a',
    fontFamily: "'Rajdhani', sans-serif",
    fontWeight: 600,
    letterSpacing: '2px',
  },
  timelineBar: {
    flex: 1,
    height: '8px',
    background: '#0d1e2e',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  timelineProgress: {
    height: '100%',
    borderRadius: '2px',
    transition: 'width 0.3s ease',
  },
  timelineValue: {
    width: '60px',
    textAlign: 'right',
    fontSize: '11px',
    fontFamily: "'Share Tech Mono', monospace",
    color: '#5a8a9a',
  },
  bottomBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '0 20px',
    height: '32px',
    background: '#060c12',
    borderTop: '1px solid #0d2d3d',
    flexShrink: 0,
  },
  statusRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  statusDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#00ff88',
    boxShadow: '0 0 8px #00ff88',
  },
  statusText: {
    fontFamily: "'Rajdhani', sans-serif",
    fontSize: '11px',
    color: '#00b060',
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.8)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: '#060c12',
    border: '1px solid #0d2d3d',
    borderRadius: '2px',
    padding: '24px',
    minWidth: '480px',
    maxWidth: '600px',
    maxHeight: '80vh',
    overflow: 'auto',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    paddingBottom: '12px',
    borderBottom: '1px solid #0d2d3d',
  },
  modalTitle: {
    fontSize: '14px',
    fontWeight: 700,
    fontFamily: "'Orbitron', monospace",
    color: '#00f5ff',
    letterSpacing: '3px',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#2a4a5a',
    fontSize: '24px',
    cursor: 'pointer',
    padding: '0',
    lineHeight: 1,
  },
  envSelector: {
    display: 'flex',
    gap: '8px',
    marginBottom: '16px',
  },
  envHeader: {
    display: 'flex',
    fontSize: '10px',
    fontWeight: 700,
    color: '#2a4a5a',
    letterSpacing: '3px',
    padding: '8px 0',
    borderBottom: '1px solid #0d2d3d',
    marginBottom: '8px',
    textTransform: 'uppercase',
  },
  envList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  envRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  envHint: {
    marginTop: '16px',
    fontSize: '11px',
    color: '#2a4a5a',
    fontFamily: "'Share Tech Mono', monospace",
    letterSpacing: '1px',
  },
  settingsSection: {
    marginBottom: '20px',
  },
};

export const styles = appStyles;
export { METHOD_COLORS };